# Generated by Django 4.2.2 on 2023-07-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('eamil1', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=10)),
                ('website1', models.CharField(max_length=50)),
                ('message1', models.TextField()),
            ],
        ),
    ]
